# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96ee7606d8b3e49e1bd8ae278de632724bf9348e9a636b8529249876064fcac3f36f401b24e4420f4c18e7880a4e9b1e99eddd5a98f1445b595cd5fea723ac57

test:
  secret_key_base: 79cbb804f8c66ba5b7ccc0b716c9604f0317361a5c60e0fff1cc4490ea39a3d25b83dcb68ab530607d49481042d9b53c3de30decaa71f5540873a5e974216348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
